name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
